### ISSUE TITLE
prepend data with imaged_moment_uuid

### ISSUE THREAD

**Issue by lonnylundsten** [kevinsbarnard/m3-download#5]
Please prepend images and all subsequent data files (i.e., voc xml, for example) with the imaged_moment_uuid. I think for long term tracking we'll need that information, in case we need to get back any additional metadata in VARS.

**Comment by kevinsbarnard** [comment]
I've added an output from the `download_images.py` script to address this. There is now a mapping from image reference UUID to (relative) filepath as downloaded.
